#!/usr/bin/env python3
"""Builds ds-bundle/, the Validatopia tokens-only design system for Claude Design.

Tokens are generated from the Validatopia Kotlin branding sources; styles.css, the guidelines and
preview cards come from .design-sync/src/; the logos are copied from the apps' resources.

Run from the repo root: python3 .design-sync/build-tokens.py
"""
import re
import shutil
from pathlib import Path

SRC = Path("samples/validatopia/shared/src/commonMain/kotlin/org/multipaz/samples/validatopia/shared/branding")
BUNDLE = Path("ds-bundle")
OUT = BUNDLE / "tokens"

shutil.rmtree(BUNDLE, ignore_errors=True)
shutil.copytree(".design-sync/src", BUNDLE)
OUT.mkdir(parents=True)
ASSETS = BUNDLE / "guidelines/assets"
ASSETS.mkdir(parents=True)
for source in ("samples/validatopia/shared/src/androidMain/res/drawable-nodpi/valid8_advisory_logo.png",
               "samples/validatopia/shared/src/androidMain/res/drawable-nodpi/valid8_advisory_logo_white.png"):
    shutil.copy(source, ASSETS)
shutil.copy("samples/validatopia/wallet-ios/ValidatopiaWallet/Assets.xcassets/EPassport.imageset/EPassport.svg",
            ASSETS / "epassport.svg")


def kebab(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


colors = (SRC / "ValidatopiaColors.kt").read_text()
consts = dict(re.findall(r'const val (\w+) = "(#[0-9A-Fa-f]{6})"', colors))


def scheme(name):
    body = re.search(r"val %s = ValidatopiaColorScheme\((.*?)\n    \)" % name, colors, re.S).group(1)
    roles = []
    for role, value in re.findall(r"(\w+) = (\"#[0-9A-Fa-f]{6}\"|[A-Z]+),", body):
        roles.append((role, consts[value] if not value.startswith('"') else value.strip('"')))
    return roles


light, dark = scheme("light"), scheme("dark")
assert len(light) == 23 and len(dark) == 23, (len(light), len(dark))


def block(selector, roles, indent=""):
    lines = [f"{indent}{selector} {{"]
    lines += [f"{indent}  --vt-color-{kebab(r)}: {v.upper()};" for r, v in roles]
    lines.append(f"{indent}}}")
    return "\n".join(lines)


brand = [(k.lower(), v) for k, v in consts.items()]
css = ["/* Generated by .design-sync/build-tokens.py from ValidatopiaColors.kt. Do not edit. */",
       "",
       "/* Brand colours, the same in both schemes. */",
       ":root {"]
css += [f"  --vt-brand-{k}: {v.upper()};" for k, v in brand] + ["}", ""]
css += ["/* Light scheme: the default. */", block(":root", light), ""]
css += ["/* Dark scheme: follows the system unless data-theme=\"light\" is set, or forced with data-theme=\"dark\". */",
        "@media (prefers-color-scheme: dark) {", block(':root:not([data-theme="light"])', dark, "  "), "}",
        block(':root[data-theme="dark"]', dark), ""]

# Card art, one background/hills/title/subtitle set per document type.
art = (SRC / "ValidatopiaCardArt.kt").read_text()
css.append("/* Document card art (ValidatopiaCardArt.kt): a background, three translucent hills, white title. */")
css.append(":root {")
for name, body in re.findall(r"val (\w+) = CardArtStyle\((.*?)\n    \)", art, re.S):
    fields = dict(re.findall(r"(background|hills|title|subtitle) = (ValidatopiaColors\.\w+|WHITE)", body))
    for field in ("background", "hills", "title", "subtitle"):
        value = fields[field]
        hexv = "#FFFFFF" if value == "WHITE" else consts[value.split(".")[1]]
        css.append(f"  --vt-card-{kebab(name)}-{field}: {hexv.upper()};")
alphas = re.search(r"hillAlphas: List<Double> = listOf\(([^)]*)\)", art).group(1)
for i, a in enumerate(x.strip() for x in alphas.split(",")):
    css.append(f"  --vt-card-hill-{i + 1}-opacity: {a};")
css.append("}")
(OUT / "colors.css").write_text("\n".join(css) + "\n")

typo = (SRC / "ValidatopiaTypography.kt").read_text()
t = ["/* Generated by .design-sync/build-tokens.py from ValidatopiaTypography.kt. Do not edit. */",
     "/* Sizes are sp on Android and pt on iOS, written here as px. Both apps use the system font. */",
     ":root {",
     '  --vt-font-family: system-ui, -apple-system, "SF Pro Text", Roboto, "Segoe UI", sans-serif;']
for name, size, line in re.findall(r"val (\w+) = TypeScaleEntry\(sizeSp = ([\d.]+)f, lineHeightSp = ([\d.]+)f\)", typo):
    t.append(f"  --vt-type-{kebab(name)}-size: {float(size):g}px;")
    t.append(f"  --vt-type-{kebab(name)}-line-height: {float(line):g}px;")
t.append("}")
(OUT / "typography.css").write_text("\n".join(t) + "\n")
print("ok", len(light), "roles,", len(brand), "brand colours")

# README: the human-editable conventions header, then an index of what's in the bundle.
header = Path(".design-sync/conventions.md").read_text().rstrip()
index = """

## Files
- `styles.css`: link this; imports the two token files and sets the body's font and colours.
- `tokens/colors.css`: brand colours, light and dark roles, card-art colours.
- `tokens/typography.css`: the type scale and system font stack.
- `guidelines/brand.md`: brand rules.
- `guidelines/colors.html`, `typography.html`, `card-art.html`, `logos.html`: preview cards.
- `guidelines/assets/`: VALID8 Advisory logos (normal and white) and the e-passport symbol.

Generated from the Validatopia apps' Kotlin branding sources
(`samples/validatopia/shared/.../branding/`) in the multipaz repository.
"""
Path("ds-bundle/README.md").write_text(header + index)

# The colour card: both schemes side by side, with literal values so it reads the same whatever
# theme the viewer's browser is in.
def swatch(label, value):
    return (f'<div class="sw"><div style="background:{value}"></div>'
            f'<div><code>{label}</code><br>{value.upper()}</div></div>')


card_style = ('<style>body{padding:16px;background:#FFFFFF;color:#0A1B37} '
              '.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:12px} '
              '.sw{border-radius:12px;border:1px solid #5A6272;overflow:hidden;font-size:14px;line-height:20px} '
              '.sw div:first-child{height:56px} .sw div:last-child{padding:6px 8px;background:#FFFFFF;color:#0A1B37} '
              'code{font-size:12px} h2{font-size:22px;line-height:28px}</style>')
sections = ["<h2>Brand</h2><div class=\"grid\">" +
            "".join(swatch(f"--vt-brand-{k}", v) for k, v in brand) + "</div>"]
for title, roles in (("Light scheme (default)", light),
                     ("Dark scheme (prefers-color-scheme: dark, or data-theme=\"dark\")", dark)):
    sections.append(f"<h2>{title}</h2><div class=\"grid\">" +
                    "".join(swatch(f"--vt-color-{kebab(r)}", v) for r, v in roles) + "</div>")
(BUNDLE / "guidelines/colors.html").write_text(
    '<!-- @dsCard group="Colors" -->\n<!doctype html><html data-theme="light"><head><meta charset="utf-8">'
    '<link rel="stylesheet" href="../styles.css">' + card_style + "<title>Colours</title></head><body>" +
    "".join(sections) + "</body></html>\n")
